# Generated by Django 3.2 on 2022-02-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('quiz_title', models.TextField(max_length=100)),
                ('detail', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_text', models.TextField(max_length=100)),
                ('quizanswer_text', models.TextField(max_length=100)),
                ('quiz_multiple', models.TextField(max_length=100)),
                ('options_one', models.CharField(max_length=100)),
                ('options_two', models.CharField(max_length=100)),
                ('options_three', models.CharField(max_length=100)),
                ('options_four', models.CharField(max_length=100)),
                ('score_quiz', models.TextField(max_length=100)),
                ('quiz_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizformative.quiz')),
            ],
        ),
    ]
