# Generated by Django 3.2 on 2022-02-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizformative', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
